### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by Zhuinden** [pawaka2020/PaleoDelights#1]
Normally I give these on Reddit, but due to... uh, given circumstances, I'm just going to do it here. (Technically I'm also available on `/r/android_devs`).

https://github.com/pawaka2020/PaleoDelights/blob/3ffd55481ea27b53dc7b69fc50ae21a56d8ab04f/app/src/main/java/com/rrdsolutions/paleodelights/OrderModel.kt#L5-L13

Same as the other project. Why mutable?

Same as other project. Why have `object OrderModel` as a namespace?

https://github.com/pawaka2020/PaleoDelights/blob/3ffd55481ea27b53dc7b69fc50ae21a56d8ab04f/app/src/main/java/com/rrdsolutions/paleodelights/OrderModel.kt#L15-L17

Revise or remove dead code.

https://github.com/pawaka2020/PaleoDelights/blob/3ffd55481ea27b53dc7b69fc50ae21a56d8ab04f/app/src/main/java/com/rrdsolutions/paleodelights/MenuModel.kt#L38-L46

This is equivalent to 

``` kotlin
nofoods = menu.foodmenu.any { it.amount == 0 }
```

.

Same for the next 3. Utilize Kotlin collection functions.

https://github.com/pawaka2020/PaleoDelights/blob/3ffd55481ea27b53dc7b69fc50ae21a56d8ab04f/app/src/main/java/com/rrdsolutions/paleodelights/MenuModel.kt#L30-L32

These variables are not referred to from outside, and should be local variables in the function.

If they weren't, they should still have been `private set`.

https://github.com/pawaka2020/PaleoDelights/blob/3ffd55481ea27b53dc7b69fc50ae21a56d8ab04f/app/src/main/java/com/rrdsolutions/paleodelights/MenuModel.kt#L22-L24

Why `var`? Why `MutableList` instead of `List`?

https://github.com/pawaka2020/PaleoDelights/blob/3ffd55481ea27b53dc7b69fc50ae21a56d8ab04f/app/src/main/java/com/rrdsolutions/paleodelights/MainViewModel.kt#L9

This `var` is never assigned and should be removed.

https://github.com/pawaka2020/PaleoDelights/blob/3ffd55481ea27b53dc7b69fc50ae21a56d8ab04f/app/src/main/java/com/rrdsolutions/paleodelights/MainViewModel.kt#L23

Same as other project, should use `enum class` to properly name the `result` of this async method.

https://github.com/pawaka2020/PaleoDelights/blob/3ffd55481ea27b53dc7b69fc50ae21a56d8ab04f/app/src/main/java/com/rrdsolutions/paleodelights/MainViewModel.kt#L35

You might want to give a callback result even when the call fails.

https://github.com/pawaka2020/PaleoDelights/blob/3ffd55481ea27b53dc7b69fc50ae21a56d8ab04f/app/src/main/java/com/rrdsolutions/paleodelights/MainActivity.kt#L38

Same as other project, Firebase initialization belongs to `Application.onCreate()`.

https://github.com/pawaka2020/PaleoDelights/blob/3ffd55481ea27b53dc7b69fc50ae21a56d8ab04f/app/src/main/java/com/rrdsolutions/paleodelights/MainActivity.kt#L125-L133

Nit: remove unnecessary whitespace.

https://github.com/pawaka2020/PaleoDelights/blob/3ffd55481ea27b53dc7b69fc50ae21a56d8ab04f/app/src/main/java/com/rrdsolutions/paleodelights/MainActivity.kt#L75

Strange how a VM is only initialized in a callback, and not in onCreate.

https://github.com/pawaka2020/PaleoDelights/blob/3ffd55481ea27b53dc7b69fc50ae21a56d8ab04f/app/src/main/java/com/rrdsolutions/paleodelights/MainActivity.kt#L89-L100

Prefer `early return` so you don't have a bunch of dangling `else {` clauses.

https://github.com/pawaka2020/PaleoDelights/blob/3ffd55481ea27b53dc7b69fc50ae21a56d8ab04f/app/src/main/java/com/rrdsolutions/paleodelights/ui/processpayment/ProcessPaymentViewModel.kt#L103

The fact that `true` means `results empty` is unclear, and should be modelled with an enum result. Theoretically you could also just pass the list.

https://github.com/pawaka2020/PaleoDelights/blob/3ffd55481ea27b53dc7b69fc50ae21a56d8ab04f/app/src/main/java/com/rrdsolutions/paleodelights/ui/processpayment/ProcessPaymentViewModel.kt#L79-L86

I can't know what type of failure happened because of boolean. Prefer enum or sealed class.

https://github.com/pawaka2020/PaleoDelights/blob/3ffd55481ea27b53dc7b69fc50ae21a56d8ab04f/app/src/main/java/com/rrdsolutions/paleodelights/ui/processpayment/ProcessPaymentFragment.kt#L59-L60

This sort of thing belongs in a destination change listener if you are using Jetpack Navigation.

https://github.com/pawaka2020/PaleoDelights/blob/3ffd55481ea27b53dc7b69fc50ae21a56d8ab04f/app/src/main/java/com/rrdsolutions/paleodelights/ui/processpayment/ProcessPaymentFragment.kt#L62

Lateinit var is assigned from Fragment to ViewModel even though it's basically setting a singleton. As it is a Singleton and not retrieved from SavedStateHandle, it is unlikely that this works correctly across process death.

There is also no reason for the VM's property to be lateinit var if it could theoretically also access the singleton.

https://github.com/pawaka2020/PaleoDelights/blob/3ffd55481ea27b53dc7b69fc50ae21a56d8ab04f/app/src/main/java/com/rrdsolutions/paleodelights/ui/processpayment/ProcessPaymentFragment.kt#L109-L117

This is equivalent to 

``` kotlin
MenuModel.menu.foodmenu.forEach { it.amount = 0 }
MenuModel.menu.drinkmenu.forEach { it.amount = 0 }
MenuModel.menu.appetizermenu.forEach { it.amount = 0 }
```

Although if the `MenuModel.menu` singleton is accessed directly, not sure why it was even set as a property on the ViewModel.

https://github.com/pawaka2020/PaleoDelights/blob/3ffd55481ea27b53dc7b69fc50ae21a56d8ab04f/app/src/main/java/com/rrdsolutions/paleodelights/ui/processpayment/ProcessPaymentFragment.kt#L146

This is a bit tricky and should probably be a RecyclerView.

https://github.com/pawaka2020/PaleoDelights/blob/3ffd55481ea27b53dc7b69fc50ae21a56d8ab04f/app/src/main/java/com/rrdsolutions/paleodelights/ui/processpayment/ProcessPaymentFragment.kt#L142

Prefer `List` over `MutableList` especially if you are not even doing edits.

And you should generally not be editing function method inputs anyway, it is preferable to build a list in the method (or create a copy to modify) then return it wrapped in `Collections.unmodifiableList()` so that nobody else can edit the copy.

https://github.com/pawaka2020/PaleoDelights/blob/3ffd55481ea27b53dc7b69fc50ae21a56d8ab04f/app/src/main/java/com/rrdsolutions/paleodelights/ui/processpayment/ProcessPaymentFragment.kt#L185-L200

If you are using Jetpack Navigation, then you are ***never supposed to overwrite the NavHostFragment***, and you are supposed to use the NavController to navigate between fragments.

https://github.com/pawaka2020/PaleoDelights/blob/3ffd55481ea27b53dc7b69fc50ae21a56d8ab04f/app/src/main/java/com/rrdsolutions/paleodelights/ui/menuitems/MenuViewModel.kt#L51-L52

When and how the initialization of your data happens is quite unclear, and if you test for process death, there is no way you won't get crashes as the MenuModel won't be set when you are from another fragment.

https://github.com/pawaka2020/PaleoDelights/blob/3ffd55481ea27b53dc7b69fc50ae21a56d8ab04f/app/src/main/java/com/rrdsolutions/paleodelights/ui/menuitems/MenuFragment.kt#L63-L84

If you ARE using LiveData to model "empty" state, why is the actual loaded data not in a LiveData?

Also, what if my network comes back, shouldn't that re-trigger a re-load of data? It's easier to save everything to local, always read from local, and only save to local when you have network. Watch https://youtu.be/8ni8RY__WeU?t=1736

https://github.com/pawaka2020/PaleoDelights/blob/3ffd55481ea27b53dc7b69fc50ae21a56d8ab04f/app/src/main/java/com/rrdsolutions/paleodelights/ui/menuitems/MenuFragment.kt#L131-L135

Your singletons will lead to unpredictable code across process death. See https://stackoverflow.com/questions/49046773/singleton-object-becomes-null-after-app-is-resumed/49107399#49107399 .

https://github.com/pawaka2020/PaleoDelights/blob/3ffd55481ea27b53dc7b69fc50ae21a56d8ab04f/app/src/main/java/com/rrdsolutions/paleodelights/ui/menuitems/MenuFragment.kt#L233-L251

You should not touch the fragment manager directly if you are using Jetpack Navigation.

https://github.com/pawaka2020/PaleoDelights/blob/3ffd55481ea27b53dc7b69fc50ae21a56d8ab04f/app/src/main/java/com/rrdsolutions/paleodelights/ui/menuitems/MenuFragment.kt#L257-L261

This is a memory leak on rotation, and there is no way this is not used for something hacky that you should not be doing at all.

https://github.com/pawaka2020/PaleoDelights/blob/3ffd55481ea27b53dc7b69fc50ae21a56d8ab04f/app/src/main/java/com/rrdsolutions/paleodelights/ui/menudetail/MenuDetailViewModel.kt#L11

Counter state is lost across process death, LiveData should be obtained from `savedStateHandle.getLiveData("counter", 0).

Also, this should not be a `var` (use `val`).

https://github.com/pawaka2020/PaleoDelights/blob/3ffd55481ea27b53dc7b69fc50ae21a56d8ab04f/app/src/main/java/com/rrdsolutions/paleodelights/ui/menudetail/MenuDetailFragment.kt#L49-L51

You probably want to use an enum for the categories, these string constants are littered all across the code.

Or at least a top-level `const val` somewhere in an `object`.

https://github.com/pawaka2020/PaleoDelights/blob/3ffd55481ea27b53dc7b69fc50ae21a56d8ab04f/app/src/main/java/com/rrdsolutions/paleodelights/ui/deliverystatus/DeliveryStatusViewModel.kt#L94

Switching based on "button text" means this is actually two separate methods, and the set of potential invalid inputs is INFINITY - 2.

You should not have `buttonText` as an input then do a switch over strings. Normally I'd say "use an enum", but here you actually just wanted 2 separate methods.

https://github.com/pawaka2020/PaleoDelights/blob/3ffd55481ea27b53dc7b69fc50ae21a56d8ab04f/app/src/main/java/com/rrdsolutions/paleodelights/ui/deliverystatus/DeliveryStatusFragment.kt#L122

Receiver is never unregistered, this is probably a memory leak.

https://github.com/pawaka2020/PaleoDelights/blob/3ffd55481ea27b53dc7b69fc50ae21a56d8ab04f/app/src/main/java/com/rrdsolutions/paleodelights/ui/aboutus/AboutUsFragment.kt#L26-L27

This stuff still belongs in a Destination change listener.

-----------

You also have 3 ViewModels that do nothing. If the ViewModel does nothing, then there is no reason to have them.

The logic of state management is randomly managed between Fragment, ViewModel, snapshot of a Singleton in a ViewModel, and in Singletons. There is no consideration for `onSaveInstanceState` or usage of `SavedStateHandle`.

Navigation is used, but then the NavHostFragment is replaced with manual fragment transactions. No wonder rotation crashes the app (as mentioned in one of the comments).

Overall, if you ever put this app in the background on a non-starter screen, and press the terminate button (refer to https://stackoverflow.com/questions/49046773/singleton-object-becomes-null-after-app-is-resumed/49107399#49107399 ) on the Logcat tab, it's unlikely that you'll get consistent results -- even though that's a core requirement of a stable and reliable Android application.

You might want to revise your usage of uncontrolled singletons managed from Fragments *and* ViewModels.

**Comment by pawaka2020** [comment]
Oh hey, thanks for the review! Sorry that I didn't check my email inbox for
the past two weeks. Thanks so much for reviewing my app. I'll fix it before
I complete finishing my resume.

By the way, I'm just wondering, do I need to do more than just these two
demo apps to be considered for a job as a junior app developer? I'm about
to apply to one job in Kuala Lumpur tomorrow.

**Comment by Zhuinden** [comment]
I'm not really the right person to ask in terms of career advice as I had a bachelor's degree in CS (technically computer engineering) and got my first job as a junior via an internship. You can always try to apply and see what happens, but beware that if they're seasoned mobile devs then they'll try to rotate the app a few times to see what happens. 😉

**Comment by pawaka2020** [comment]
Oh nice! Note to self, make sure all my demo apps are rotate-proof.

I guess I'll re-enable the landscape mode then, even if the app looks ugly
in landscape mode. I just want to see them try to rotate my app over and
over, haha.

**Comment by pawaka2020** [comment]
Hey there, gonna need your expert advice in this if you don't mind.  In this particular app, I have to download the menu items from my Firebase database, and then actually -keep- the downloaded instance as I move from MenuFragment to MenuDetailFragment so that I can modify the amount of menu items ordered. 

What would be the best solution for this? I considered a number of different ones, like saving the instance of the menu items into a SharedPreference and then remembering to delete it once I am done with using it (ie. after submitting the modified menu item instance as a customer order in ProcessPaymentFragment). I try this time not to rely on using singletons as a quick solution for this.

**Comment by Zhuinden** [comment]
AFAIK Firebase caches query results locally, so I'd just execute the same query with the same parameters on the other screen.

Especially considering we're talking about a detail fetch but reusing the list and indexing by hand is always a bit of a pain, so I wouldn't try to share the full result set to the detail result.

**Comment by pawaka2020** [comment]
I see. Would your solution work if the Firebase query is made from a different ViewModel? I'm trying it right now.
